# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [ ]:
# Crie um array NumPy com 1.000.000 e uma lista com 1.000.000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [1]:
import numpy as np

In [116]:
a = np.arange(0,1000000)
b = list(range(0, 1000000))

In [117]:
a = %time (a * 2)
a

Wall time: 3.64 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [118]:
%time [x*2 for x in b]

Wall time: 148 ms


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

### Exercício 2

In [119]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0
a = np.arange(0,10)
a[5:9] = 0
a

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 9])

### Exercício 3

In [162]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
a = np.arange(15).reshape(3,5)
a[0]

array([0, 1, 2, 3, 4])

### Exercício 4

array([11,  6,  4, 13,  2, 12, 14, 13,  2,  1, 12,  0,  9,  0,  2])

In [265]:
# Crie um array de duas dimensões (matriz).

rd = np.random
# rd.seed(0)
matrix = rd.randint(0, 100, 15).reshape(3,5)

print(matrix)
print('\n')
# Imprima os elementos da terceira linha da matriz

print(matrix[2])
print('\n')

# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

print(matrix[0:2, 1:3])

[[ 4 67 11 86 77]
 [75 56 16 24 29]
 [21 25 80 60 61]]


[21 25 80 60 61]


[[67 11]
 [56 16]]


### Exercício 5

In [277]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
print(arr)
print('\n')
print(arr.transpose())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [287]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

[xarr[i] if x else yarr[i] for i,x in enumerate(cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [293]:
# Crie um array A com 10 elementos
a = np.arange(10)

# e salve o array em disco com a extensão npy
np.save('array_a', a)

# Depois carregue o array do disco no array B
b = np.load('array_a.npy')
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 8

In [305]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [485]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [486]:
pd.DataFrame(resp.json())

assignee  \
0                                                None   
1                                                None   
2                                                None   
3                                                None   
4                                                None   
5                                                None   
6                                                None   
7                                                None   
8                                                None   
9                                                None   
10                                               None   
11                                               None   
12                                               None   
13                                               None   
14                                               None   
15                                               None   
16                                               None   
17                                               None   
18                                               None   
19                                               None   
20                                               None   
21                                               None   
22                                               None   
23                                               None   
24                                               None   
25                                               None   
26                                               None   
27                                               None   
28                                               None   
29  {'login': 'bdice', 'id': 3943761, 'node_id': '...   

                                            assignees author_association  \
0                                                  []        CONTRIBUTOR   
1                                                  []             MEMBER   
2                                                  []        CONTRIBUTOR   
3                                                  []             MEMBER   
4                                                  []             MEMBER   
5                                                  []               NONE   
6                                                  []             MEMBER   
7                                                  []               NONE   
8                                                  []             MEMBER   
9                                                  []        CONTRIBUTOR   
10                                                 []             MEMBER   
11                                                 []             MEMBER   
12                                                 []        CONTRIBUTOR   
13                                                 []             MEMBER   
14                                                 []               NONE   
15                                                 []               NONE   
16                                                 []        CONTRIBUTOR   
17                                                 []               NONE   
18                                                 []        CONTRIBUTOR   
19                                                 []               NONE   
20                                                 []               NONE   
21                                                 []             MEMBER   
22                                                 []             MEMBER   
23                                                 []               NONE   
24                                                 []             MEMBER   
25                                                 []               NONE   
26                                                 []               NONE   
27                                                 []               NONE   
28                                                 []               NONE 

### Exercício 10

In [553]:
'|'.join({'name':'text','value':'float','qtd':'int'})

'name|value|qtd'

In [21]:
def data_delete(table, _id=[]):
    command = "DELETE FROM {} WHERE id IN ({})"
    command = command.format(table, ", ".join([str(i) for i in _id]))
    return command

data_delete('produto', [1])

'DELETE FROM produto WHERE id IN (1)'

In [63]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

import sqlite3

def execute(command):
    # Criando uma conexão
    conn = sqlite3.connect('exercicio10.db')   
    # Criando um cursor
    cursor = conn.cursor()
    
    cursor.execute(command)
    fetchall = cursor.fetchall()
    
    conn.commit()
    cursor.close()
    conn.close()
    
    return fetchall
    
# Função para criar uma tabela
def create_table(table='', cols=[]):
    command = "CREATE TABLE IF NOT EXISTS {} (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, {})"
    command = command.format(table, ", ".join(cols))
    execute(command)
    
# Função para criar uma tabela
def drop_table(table):
    command = "DROP TABLE {}".format(table)
    execute(command)
    
# Função para inserir uma linha
def data_insert(table, cols=[], values=[]):
    command = "INSERT INTO {}({}) VALUES({})"
    command = command.format(table,", ".join(cols), ", ".join([str(i) if type(i) in (int,float) else "\'{}\'".format(i) for i in values]))
    execute(command)

def data_delete(table, _id=[]):
    command = "DELETE FROM {} WHERE id IN ({})"
    command = command.format(table, ", ".join([str(i) for i in _id]))
    execute(command)
    
# Leitura de dados
def data_select_all(table):
    fetchall = execute("SELECT * FROM {}".format(table))
    return [linha for linha in fetchall]
        
# Leitura de dados
def data_select_by_id(table, _id):
    fetchall = execute("SELECT * FROM {} WHERE id IN ({})".format(table, ",".join([str(i) for i in _id])))
    return [linha for linha in fetchall]

In [23]:
table = 'produto'

In [49]:
create_table(table, ['nome TEXT','valor REAL','qtd INTEGER'])

In [58]:
data_insert(table, ['nome','valor','qtd'], ['notebook',5000.00,2])

In [66]:
data_select_all(table)

[(3, 'notebook', 5000.0, 2),
 (4, 'notebook', 5000.0, 2),
 (5, 'notebook', 5000.0, 2),
 (6, 'notebook', 5000.0, 2),
 (7, 'notebook', 5000.0, 2)]

In [65]:
data_select_by_id(table, [2,3])

[(3, 'notebook', 5000.0, 2)]

In [67]:
data_delete(table, [1,2])

In [68]:
data_select_all(table)

[(3, 'notebook', 5000.0, 2),
 (4, 'notebook', 5000.0, 2),
 (5, 'notebook', 5000.0, 2),
 (6, 'notebook', 5000.0, 2),
 (7, 'notebook', 5000.0, 2)]

In [74]:
import pandas as pd
df = pd.DataFrame(data_select_all(table), columns=['id','nome','valor','qtd'])
df

id      nome   valor  qtd
0   3  notebook  5000.0    2
1   4  notebook  5000.0    2
2   5  notebook  5000.0    2
3   6  notebook  5000.0    2
4   7  notebook  5000.0    2

In [75]:
drop_table(table)

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>